#!/bin/bash

help() {
  script_name=jboss-cli
echo "
$script_name is a Kubernetes plugin to connect to all WildFly server belonging to an application and run jboss-cli sessions on all of them.
Usage:
  $script_name apply-script <labels> <cli file>
Where the parameters are:
  * <labels> - Labels that match the application pods
  * <cli file> - File containing the CLI commands to run on each WildFly server
"
exit 1
}

LABELS=$1
FILE=$2
REMOTE_FILE=/tmp/$(basename $FILE)
if [ "x$LABELS" == "x" ]; then
help
fi

PODS=$(kubectl get pods -o jsonpath={..metadata.name} -l $LABELS)

# copy the file on each pod
for pod in $PODS
do
  kubectl cp $FILE $pod:$REMOTE_FILE
done

for pod in $PODS
do
  echo "Running on $pod"
  kubectl exec -it ${pod} -- sh -c "[ -e /opt/jboss/container/wildfly-bootable-jar/install-dir ] && JBOSS_HOME=\$( cat /opt/jboss/container/wildfly-bootable-jar/install-dir ); \$JBOSS_HOME/bin/jboss-cli.sh -c --file=$REMOTE_FILE"
done