= kubectl-jboss-cli - Kubernetes Plugin to run jboss-cli 
:toc:               left

This plugin connects to a WildFly server running inside a Kubernetes Pod and creates a jboss-cli session connected to the server.
It can also connect to a server running inside a bootable jar.

== Prerequisites

* `kubectl` or `oc` is installed

== Installation

[source,shell]
----
curl -O -sL https://raw.githubusercontent.com/jmesnil/kubectl-jboss-cli/main/kubectl-jboss_cli-pod
curl -O -sL https://raw.githubusercontent.com/jmesnil/kubectl-jboss-cli/main/kubectl-jboss_cli-app
curl -O -sL https://raw.githubusercontent.com/jmesnil/kubectl-jboss-cli/main/kubectl-jboss_cli-apply_script
chmod u+x ./kubectl-jboss_cli-*
export PATH=$PATH:.
----

== Usage

=== Run commands on a single WildFly server

[source,shell]
----
kubectl jboss-cli pod <pod name> <jboss-cli parameters>
----

==== Examples

===== Interactive session

[source,shell]
----
$ kubectl get pods
NAME                         READY   STATUS    RESTARTS   AGE
...
my-app-77d65cb876-9p242               1/1     Running     0          38s
my-app-77d65cb876-hhsv8               1/1     Running     0          56m
...

$ kubectl jboss-cli pod my-app-77d65cb876-9p242
[standalone@localhost:9990 /] ls
core-service                               subsystem                                  namespaces=[]                              release-version=17.0.3.Final
deployment                                 system-property                            organization=undefined                     running-mode=NORMAL
deployment-overlay                         launch-type=STANDALONE                     process-type=Server                        runtime-configuration-state=ok
extension                                  management-major-version=18                product-name=WildFly Full                  schema-locations=[]
interface                                  management-micro-version=0                 product-version=25.0.1.Final               server-state=running
path                                       management-minor-version=0                 profile-name=undefined                     suspend-state=RUNNING
socket-binding-group                       name=my-app-77d65cb876-9p242               release-codename=                          uuid=a2bbbb96-238c-4366-baaf-3cfebf16bc35

[standalone@localhost:9990 /] :read-attribute(name=product-version)
{
    "outcome" => "success",
    "result" => "25.0.1.Final"
}
----

===== Run a non-interactive session with a single command

[source,shell]
----
$ kubectl jboss-cli pod my-app-77d65cb876-9p242 --command=':read-attribute\(name=product-version\)'
{
    "outcome" => "success",
    "result" => "25.0.1.Final"
}
----

=== Run commands on all WildFly servers belonging to an application

[source,shell]
----
kubectl jboss-cli app <label selector> <jboss-cli parameters>
----

==== Examples

===== Run a non-interactive session with a single command


[source,shell]
----
$ kubectl get pods -l app.kubernetes.io/instance=my-app
NAME                      READY   STATUS    RESTARTS   AGE
my-app-77d65cb876-9p242   1/1     Running   0          3m12s
my-app-77d65cb876-hhsv8   1/1     Running   0          59m
----

All the pods that belong to the `my-app` application have the label `app.kubernetes.io/instance=my-app`

[source,shell]
----
$ kubectl jboss-cli app app.kubernetes.io/instance=my-app --commands=":read-attribute\(name=name\),:read-attribute\(name=uuid\)"
Running on pod/my-app-77d65cb876-9p242
{
    "outcome" => "success",
    "result" => "my-app-77d65cb876-9p242"
}
{
    "outcome" => "success",
    "result" => "a2bbbb96-238c-4366-baaf-3cfebf16bc35"
}
Running on pod/my-app-77d65cb876-hhsv8
{
    "outcome" => "success",
    "result" => "my-app-77d65cb876-hhsv8"
}
{
    "outcome" => "success",
    "result" => "b035c7e9-0898-4c15-9426-15a603b554f5"
}
----

=== Apply a script to all WildFly servers belonging to an application

[source,shell]
----
kubectl jboss-cli apply-script <labels> <script file>
----

==== Examples

===== Change the log level for the console output

[source,shell]
----
$ cat change-log-level.cli
/subsystem=logging/console-handler=CONSOLE:write-attribute(name=level,value=DEBUG)
/subsystem=logging/root-logger=ROOT:write-attribute(name=level,value=DEBUG)

$ kubectl jboss-cli apply-script app.kubernetes.io/instance=my-app ./change-log-level.cli
----
