= kubectl-jboss-cli - Kubernetes Plugin to run jboss-cli 
:toc:               left

This plugin connects to a WildFly server running inside a Kubernetes Pod and creates a jboss-cli session connected to the server.
It can also connect to a server running inside a bootable jar.

== Prerequisites

* `kubectl` or `oc` is installed

== Installation

[source,shell]
----
curl -sL https://raw.githubusercontent.com/jmesnil/kubectl-jboss-cli/main/install.sh | bash
----

== Usage

[source,shell]
----
$ kubectl jboss-cli -h

jboss-cli is a Kubernetes plugin to connect to WildFly servers running in pods and run jboss-cli sessions.

Usage:

  jboss-cli [-h]
     - Displays this help
  jboss-cli [-p <pod>] [-f file] [-- <jboss-cli parameters>]
     - Connects to a single pod
  jboss-cli [-l <pod selector label>] [-f file] [-- <jboss-cli parameters>]
      - Connects to multiple pods matching the label

Where the parameters are:
  * <pod> - Name of the pod running the application image
  * <pod selector label> - Labels to select all the pods belonging to the application
  * <file> - A file containing CLI commands
  * <jboss-cli parameters> - Parameters passed to the jboss-cli session (including --command, --commands, etc.)
----

== Examples

=== Prerequisites

You need to be logged in to a Kubernetes cluster that is up and running (for example with `minikube`).

Let's create a `my-app` deployment with 3 replicas and the label `app=my-app`:

[source,shell]
----
kubectl create deployment my-app --replicas=3 --image=quay.io/wildfly/wildfly
----

The deployment is composed of 3 pods:

[source,shell]
----
$ kubectl get deployment my-app
NAME     READY   UP-TO-DATE   AVAILABLE   AGE
my-app   3/3     3            3           66s
$ kubectl get pods
NAME                      READY   STATUS    RESTARTS   AGE
my-app-84b45f6b74-6xldb   1/1     Running   0          69s
my-app-84b45f6b74-ct8g4   1/1     Running   0          69s
my-app-84b45f6b74-m824q   1/1     Running   0          69s
----

=== Run commands on a single WildFly server

[source,shell]
----
kubectl jboss-cli -p <pod name> -- <jboss-cli parameters>
----

==== Interactive session

[source,shell]
----
$ kubectl jboss-cli -p my-app-84b45f6b74-6xldb
Running on my-app-84b45f6b74-6xldb
[standalone@localhost:9990 /] ls
core-service                               socket-binding-group                       management-minor-version=0                 product-version=34.0.1.Final               schema-locations=[]
deployment                                 subsystem                                  name=my-app-84b45f6b74-6xldb               profile-name=undefined                     server-state=running
deployment-overlay                         system-property                            namespaces=[]                              release-codename=                          suspend-state=RUNNING
extension                                  launch-type=STANDALONE                     organization=undefined                     release-version=26.0.1.Final               uuid=5a1bcc3b-ffb1-4c32-9c96-ce47173b0441
interface                                  management-major-version=27                process-type=Server                        running-mode=NORMAL
path                                       management-micro-version=0                 product-name=WildFly                       runtime-configuration-state=ok
[standalone@localhost:9990 /] :read-attribute(name=product-version)
{
    "outcome" => "success",
    "result" => "34.0.1.Final"
}
----

==== Non-interactive session

[source,shell]
----
kubectl jboss-cli -pmy-app-84b45f6b74-6xldb -- --command=":read-attribute\(name=product-version\)"
Running on my-app-84b45f6b74-6xldb
{
    "outcome" => "success",
    "result" => "34.0.1.Final"
}
----

[NOTE]
=====
The parentheses in the CLI commands must be escaped with `\` when the session is non-interactive.
=====

=== Run commands on all WildFly servers belonging to an application

[source,shell]
----
kubectl jboss-cli -l <label selector> -- <jboss-cli parameters>
----

==== Non-interactive session

All the pods that belong to the `my-app` deployment have the label `app=my-app`.

[source,shell]
----
$ kubectl jboss-cli -l app=my-app -- --commands=":read-attribute\(name=name\),:read-attribute\(name=uuid\)"
Running on my-app-84b45f6b74-6xldb
{
    "outcome" => "success",
    "result" => "my-app-84b45f6b74-6xldb"
}
{
    "outcome" => "success",
    "result" => "5a1bcc3b-ffb1-4c32-9c96-ce47173b0441"
}
Running on my-app-84b45f6b74-ct8g4
{
    "outcome" => "success",
    "result" => "my-app-84b45f6b74-ct8g4"
}
{
    "outcome" => "success",
    "result" => "1110f54f-5762-4ce6-91fd-b45601cbd0bd"
}
Running on my-app-84b45f6b74-m824q
{
    "outcome" => "success",
    "result" => "my-app-84b45f6b74-m824q"
}
{
    "outcome" => "success",
    "result" => "527761ea-a529-42d9-b4b6-b354f2748229"
}
----

=== Apply a script to all WildFly servers belonging to an application

[source,shell]
----
kubectl jboss-cli -l <labels> -f <script file>
----

==== Change the log level for the console output

[source,shell]
----
$ cat change-log-level.cli
/subsystem=logging/console-handler=CONSOLE:write-attribute(name=level,value=DEBUG)
/subsystem=logging/root-logger=ROOT:write-attribute(name=level,value=DEBUG)

$ kubectl jboss-cli -l app=my-app -f ./change-log-level.cli
Running on my-app-84b45f6b74-6xldb
{"outcome" => "success"}
{"outcome" => "success"}
Running on my-app-84b45f6b74-ct8g4
{"outcome" => "success"}
{"outcome" => "success"}
Running on my-app-84b45f6b74-m824q
{"outcome" => "success"}
{"outcome" => "success"}
----